services:
  app-dev:
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    env_file: .env
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
      - sports-db
    profiles:
      - dev

  app-prod:
    build:
      context: ./
      dockerfile: ./app/prod.Dockerfile
    env_file: .env
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - db
      - sports-db
    profiles:
      - prod
      
  db:
    build:
      context: ./db
    env_file: .env
    ports:
      - $PB_PORT:$PB_PORT
    volumes:
      - ./db/migrations:/pb/pb_migrations
      - ./db/data:/pb/pb_data
      - ./db/hooks:/pb/pb_hooks
    profiles:
      - dev
      - prod

  sports-db:
    build:
      dockerfile: ../db/Dockerfile
      context: ./sports_db
    env_file: .env
    ports:
      - $SPORTS_PB_PORT:$PB_PORT
    volumes:
      - ./sports_db/migrations:/pb/pb_migrations
      - ./sports_db/data:/pb/pb_data
    profiles:
      - dev
      - prod

volumes:
  node_modules: