export const sportsPriority = [
    'football',
    'ultimate frisbee',
    'skating',
    'squash',
    'table tennis',
    'pool',
    'hockey',
    'chess',
    'tennis',
    'cricket',
    'athletics',
    'powerlifting',
    'swimming',
    'carrom',
    'throwball',
    'kabbadi',
    'badminton',
    'snooker',
    'volleyball',
];